version: "3.9"
services:
    http_server:
        build: .
        depends_on:
            - grpc
        ports:
            - "127.0.0.1:8002:8080"
        entrypoint: ["httpServer", "0.0.0.0", "8080"]
    tcp_server:
        build: .
        ports:
            - "127.0.0.1:8001:8001"
        entrypoint: ["tcpServer", "8001"]
    grpc:
        build: .
        ports:
            - "127.0.0.1:8000:8000"
        entrypoint: ["dbLayerRPCServer", "0.0.0.0", "8000"]
